### ISSUE TITLE
Whole HDD disk copy fails with 2.5.0a2

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#10] opened 2019-08-25 07:18 UTC
Whole HDD disk copy fails with 2.5.0a2

BUG

2.5.0
## Description

I was using CAT.DOCTOR to copy one HDD partition on MicroDrive/Turbo to another.  About 8MB total.  Works fine with ProDOS 2.4.2 but craps out at the same spot every time under 2.5.2a2, with "MLI Error $56' (if I recall correctly.)

## Expected Behavior

Should copy all files without error.

## Actual Behavior

Stops with error, apparently at the same point on each transfer.  The failing file in the spelling dictionary for AppleWorks 4.3, which is 350 blocks or so in size.

## Possible Fix

No idea, but it doesn't happen with 2.4.2.

## Steps to Reproduce

1. Boot ProDOS 2.5.0a2
2. Using Bitsy Bye, start CAT.DOCTOR 6.8
3. Hit P to disable prompts
4. Hit W and wipe the destination volume (/H4 in my case)
5. Hit X and choose /H1 as source and /H4 as destination
6. In the file chooser screen hit <Ctrl>-A to select all.
7. Hit <Return> to start copy.

## Context

Was trying to back up one partition to the other.

## Your Environment

Source and destination partitions are partition number 1 and 4 on MicroDrive/Turbo.  Each 32MB.

### Hardware:

Apple //e Enhanced, 128K, MicroDrive/Turbo in slot 7.

### ProDOS8 version:
2.5.0a2

### Non-Operating System release software being used: 
CAT.DOCTOR 6.8 - The one that comes with ProSEL 4.0

**Comment by bobbimanners** [comment] 2019-08-25 07:45
Was CAT.DOCTOR 6.7, not 6.8.  (Haven't tried this with 6.8)

**Comment by JohnMBrooks** [comment] 2019-08-26 03:00
I was unable to reproduce this problem using Cat.Doctor 6.8 and copies all files from one 5.25 floppy to another.

Can you see if you can reproduce the problem with v6.8 and floppy disks?

**Comment by bobbimanners** [comment] 2019-08-26 15:36
I doubt I am going to be able to reproduce it copying a floppy.

I have only seen this error when copying all the files on a hard drive from one partition to another.  It fails with 2.5.0a2 after having copied quite a few directories.  I have only seen it fail twice, but it was on the same file each time.  I thought I had some weird disk corruption at first but MR.FIXIT says all is good, and when I booted 2.4.2 I was able to copy the entire drive.  So it seems like a regression.

I will try again with 2.5.0a3 and see if it happens.  Fortunately I have a few spare partitions to play with.  If necessary I can send you my 32MB disk image ...

I will also try with CAT.DOCTOR 6.8 rather than 6.7 on the off chance this makes a difference.  (What are the changes in CAT.DOCTOR anyhow?  Was 6.8 an original release or is it Y2K patched or something?)

**Comment by DevoKun** [comment] 2019-08-26 15:41
You say that the test fails on the same file every time. What file is that?

If you can share the disk image with us that would be very helpful.

Thanks,


--
*Devon P. Hubner*
  devon@hubner.org

*  603-313-6916*

**Comment by bobbimanners** [comment] 2019-08-26 15:48
It is the spell-check dictionary of Appleworks 4.3 if I recall correctly.  (Maybe AW 3.0, I have all of them installed.)  I was able to copy the files using the Aztec C SHELL.SYSTEM under ProDOS 2.5.0a2, so I guess CAT.DOCTOR is doing things differently.

Basically what I am doing is running CAT.DOCTOR 6.8 (the one that came with ProSEL 4.0 as distributed on Asimov) and doing the following:
- Press 'P' to turn off prompting
- Press 'W' and choose to wipe partition /H4 (fourth partition on my MicroDrive)
- Press 'X' and choose to copy /H1 to /H1 (first partition to fourth partition)
- Press Ctrl-A to select all files
- Hit return
- Get coffee and wait for an MLI error ;)

**Comment by bobbimanners** [comment] 2019-08-26 15:48
I can grab you the disk image later today with any luck.

**Comment by bobbimanners** [comment] 2019-08-26 22:16
Confirmed that this still fails with ProDOS 2.5.0a3 and CAT.DOCTOR 6.7.

Currently trying with CAT.DOCTOR 6.8 (the one that comes with ProDOS 2.4.2)

**Comment by bobbimanners** [comment] 2019-08-26 22:22
It also happens with CAT.DOCTOR 6.8.

The file that causes the error upon copying is /H1/APPLEWORKS.4.3/MAIN.DICTIONARY.

Error is MLI Error $56

The entire filesystem copies without issue under ProDOS 2.4.2.

I will try and dump the filesystem for you tomorrow, but it is nothing special.  I can also reproduce the error copying just that file in CAT.DOCTOR.

I am going to play some more - I will post an update if I have any worthwhile observations.

**Comment by bobbimanners** [comment] 2019-08-26 22:41
Some more info ... turns out I can reproduce this with just the one file (MAIN.DICTIONARY from AW4.3).

- Under ProDOS 2.5.0a3, using Aztec C SHELL.SYSTEM: I can copy MAIN.DICTIONARY using the cp command with no problem.
- Under ProDOS 2.5.0a3, using CAT.DOCTOR 6.8, I get MLI Error $56 copying this same file.
- Boot ProDOS 2.4.2.  Now I am able to copy the file using CAT.DOCTOR 6.8 with no problem.  I copied the file to /H3/MAIN.DICTIONARY.  (/H3 is an otherwise empty volume.)
- Boot ProDOS 2.5.0a3 again.  Try to copy /H3/MAIN.DICTIONARY to the same directory, renaming as NEW.  Fails with MLI Error $56.

Now I can reproduce this with just the MAIN.DICTIONARY file and an empty filesystem.  The weird thing is this only seems to happen with 2.5.0 and CAT.DOCTOR, and this particular file.  I am very curious as to what can cause this weird breakage!

Can I upload the offending file somewhere for you guys?

**Comment by bobbimanners** [comment] 2019-08-26 23:29
I emailled the file in question.  It would be nice to test this using a floppy only, but the file is bigger than 143K.

**Comment by bobbimanners** [comment] 2019-08-31 05:05
I attached an 800k disk image with the problem file `MAIN.DICTIONARY` in the conversation thread for ticket #5

**Comment by bobbimanners** [comment] 2019-08-31 05:11
Easy to reproduce with the disk image `800k-problems2.po` (see ticket #5 )

1. Boot ProDOS 2.5.0a3 from another volume (my disk isn't bootable)
2. Browse to slot 5, disk 1 in Bitsy Bye
3. Select and run `CAT.DOCTOR`
4. 'X' for copy, source `/PROBLEMS`, dest `/PROBLEMS`
5. Pick the file `MAIN.DICTIONARY`
6. When prompted, enter a new filename `FOOBAR`
7. Observe MLI Error $56

**Comment by JohnMBrooks** [comment] 2019-09-01 16:42
Confirmed the bug using supplied disk PROBLEMS2. I then tried copying main.dictionary using Copy II+ 8.2 which worked successfully.

I will investigate why C2+ works and CD does not under P8 2.5.0.

**Comment by bobbimanners** [comment] 2019-09-01 21:36
I am glad you could reproduce this.  It is a weird one - needs a certain ProDOS, a certain file and also a certain tool.  It is like lining up all the reels on the fruit machine :)

**Comment by JohnMBrooks** [comment] 2019-09-02 03:41
Fixed in 2.5.0a4. The problem was that when I optimized the test for the $BF58 memory page bits, it checked one extra page past the pages being loaded into. Cat doctor loads into page $BE00, which was failing because 2.5.0a3 thought it was trying to load into $BF00 which is illegal.

**Closed as completed by JohnMBrooks** 2019-09-02 03:41 UTC

**Comment by bobbimanners** [comment] 2019-09-02 21:15
Confirmed fixed in 2.5.0a4.  Thank you :)

**Comment by JohnMBrooks** [comment] 2019-09-02 21:48
If the grab the latest version, it will auto-convert day/month/year from the old date format on disks to the new extended format.
