### ISSUE TITLE
ProDOS8 2.5.0 alpha 6 - Crash when FASTchip //e accelerator installed

### ISSUE THREAD

**Issue by jormahonkanen** [ProDOS-8/ProDOS8-Testing#24] opened 2019-09-16 17:07 UTC
## Description

Crash when using FASTchip //e (a2heaven.com)

## Expected Behavior

Crash to monitor when FASTchip //e accelerator is installed

## Steps to Reproduce

1.
2.
3.
4.

## Your Environment

Apple //e platinum 128k NTSC

### Hardware:

Slot 1 FASTCHIP //e
Slot 2 TimeMaster II H.O. (a2heaven.com)
Slot 3 Uthernet II
Slot 4 MEGAaudio
Slot 5 -empty- for CFFA3000 floppy emulation
Slot 6 Disk II interface 
Slot 7 CFFA3000 & CF (hdd emulation)
AUX RAMWorksIIII+VGA

### ProDOS8 version:
ProDOS8 2.5.0 alpha 6

### Non-Operating System release software being used: 
None

**Comment by JohnMBrooks** [comment] 2019-09-16 17:18
What kind of crash? During boot? Can you provide a screenshot/photo?

**Comment by jormahonkanen** [comment] 2019-09-16 17:31
Here,

ma 16. syysk. 2019 klo 20.18 JohnMBrooks <notifications@github.com>
kirjoitti:

**Comment by jormahonkanen** [comment] 2019-09-16 17:37
Jumps to monitor:
2035 - A=CA X=26 Y=CA P=F3 S=FB
*

The same happens if boot 2.4.2 from CFFA3000 and then boot 2.5.0x from floppy (with FASTchip //e card installed)

FASTCHIP //e in Slot 1
65C02 *IS* installed in the main logic board.

**Comment by JohnMBrooks** [comment] 2019-09-16 18:03
What speed is FASTCHIP running at?
What happens if FASTCHIP is disabled?
What happens if 2.5.0 is booted from CFFA smartport instead of CFFA floppy emulation?

**Comment by joelmcw** [comment] 2019-09-17 00:58
You may have some other issue. I have an Apple //e Platinum with the following configuration and I can boot 2.5.0a3 with no problems. Granted I haven’t tried to run much but I am not crashing to the monitor.
 
Joel Mc
 
Aux – Ramworks III+VGA scaler
Slot 1 – Fastchip //e (A2Heaven.com)
Slot 2 – Super Serial
Slot 3 – VidHD
Slot 4 – Mockinboard
Slot 5 – CFFA (virtual floppy)
Slot 6 – Disk II controller
Slot 7 – CFFA 3000 (latest version)

**Comment by JohnMBrooks** [comment] 2019-09-17 01:23
Thanks Jorma & Joel!

Jorma, what slot is your CFFA floppy emulation set to?
Also, is the FastChip emulating a RamFactor card, and if so, what slot is it using?

I have run into weird crashes when the CFFA or FastChip emulated devices get mapped to an slot occupied by another physical or emulated card. Perhaps that is happening here?

**Comment by jormahonkanen** [comment] 2019-09-17 05:34
Additional information:
-Fastchip //e running at 1Mhz (at this time). Set to normal or fast, doesn't matter (at Fastchip config)
-Boots ok if Fastchip is disabled OR removed.
-My CFFA floppy emulation is set to slot 5.
-When disk image is booted from CFFA crashes the same way (as if Fastchip installed/enabled)
-Fastchip Ramfactor and Ramworks emulations are both *off*.

I'll test more when with more time. It's clearly Fastchip releated matter somehow. I'll see if i install it to an another slot etc.

**Comment by jormahonkanen** [comment] 2019-09-17 12:13
I have two Fastchip //e cards, first is pre production with firmware 0.1b is loads up but then stops at the ........ the other one is 0.5b and that is the one i've used. Just tested these both now.

John & Joel - what firmware your cards have?

**Comment by jormahonkanen** [comment] 2019-09-17 12:43
Apple //e NTSC enhanced

Fastchip settings : Slot 1 fast, all others slow

Slot 1 - Fastchip //e (firmware 0.5b)
Slot 2 - Empty
Slot 3 - Empty
Slot 4 - Empty
Slot 5 - Reactive Drive/Turbo
Slot 6 - DIsk II interface card + wDrive
Slot 7 - VGA scaler
AUX - RamWorks 8M (a2heaven)

Crash to monitor:
2035- A=E0 X=86 Y=CA P=F1 S=FB (varies)
*

Boots ok when disabled.

Starts to look it's Fastchip //e issue.

Tested for the fun of it with Transwarp (fw 1.4) in slot 3 and it boots fine.

**Comment by jormahonkanen** [comment] 2019-09-17 14:48
Plamen Vaysilov, the maker of the Fastchip, suggested to check what manufacturer you guys have on IOU chips?

**Comment by joelmcw** [comment] 2019-09-17 16:18
My Fastchip //e is running firmware 0.5b. 
 
My MMU and IOU labeled AMI, Apple 82, Philippines.
 
For what it’s worth, I am booting P8 2.5.0a3 from USB image and can run programs (Appleworks 5, Merlin, Games, etc) from any mounted volume and have not had my system to crash to the monitor.  Also, it doesn’t seem to matter what speed I run the FastChip 1mhz-16.6Mhz.
 
Joel Mc
 
Apple //e Platinum
Aux – Ramworks III+VGA scaler
Slot 1 – Fastchip //e (A2Heaven.com)
Slot 2 – Super Serial
Slot 3 – VidHD
Slot 4 – Mockingboard
Slot 5 – CFFA (virtual floppy)
Slot 6 – Disk II controller
Slot 7 – CFFA 3000 (latest version)

**Comment by JohnMBrooks** [comment] 2019-09-17 17:34
Joel, can you try testing with this 2.5.0a6 preview?

https://drive.google.com/open?id=1n6ksz5DPddFRx3f0swJV2xcNwdKKIAL_

**Comment by joelmcw** [comment] 2019-09-17 18:16
Yes, will do as soon as I get home.

⁣Joel Mc​

**Comment by joelmcw** [comment] 2019-09-17 19:21
John,
 
I have tested P8 2.5.0a6 and still cannot cause a crash to the monitor running various programs.  However, I did discover a different issue that I do not see with 2.5.0a3 (I didn’t test a4 or a5) as follows:
 
My CFFA is in slot 7. I am booting P8 2.5.0a6.dsk from CFFA/USB assigned to virtual floppy d1 (slot5), AdtPro.dsk assigned to virtual floppy d2 (slot5). I have three 32mb volumes assigned on CFFA/CF.
 
Under 2.50.a6 they are getting mounted as:
 
P8 2.5.0a6.dsk --  slot 5, d1
AdtPro.dsk -- slot 5,d2
P8 2.4.2 .2mg -- slot 7,d1
A2Games.po – slot 7,d2
TotalReplay.2mg – slot 7,d3
 
Since the Total Replay volume is getting mounted as a 3rd drive on slot7 rather than slot 4,d1 (as it did using 2.5.0.a3), it is causing Total Replay to hang (black screen) when attempting to run it.  
 
Joel Mc

**Comment by JohnMBrooks** [comment] 2019-09-18 02:12
Hi Joel,

It is likely that Total Replay and other apps which directly call a drive's card ROM driver will need an update/mod to take advantage of drives 3-8 on P8 2.5.0.

In addition to mounting up to 37 drives, a goal of the new 8-drive feature is to make it easier & more-reliable for apps which use ProRWTS to find the smartport driver and device from which they are being launched.

**Comment by joelmcw** [comment] 2019-09-18 02:43
John,

Ok, that makes sense. So far I have not experienced any other issues with 2.5.0a6 but will continue to test.

Thanks!

⁣Joel Mc​

**Comment by jormahonkanen** [comment] 2019-09-18 04:38
I think i'll test with RamWorks card removed and replaced with Apple's own 80col/64k card. But that i'll do with the enhanced //e first.

**Comment by roughana** [comment] 2019-09-18 23:16
Total Replay v1 will hang if trying to load from Smartport device 5+.
Total Repay v2 (beta2+) will display message RUN FROM PARTITION 1-4

ProDOS 2.5.0A6 boots for me Platinum //e International - IOU Korea 344-0022-B
Slot 1: FastChip //e (RamWorks and RamFactor off) 0.4b
Slot 3: VidHD v1.16a
Slot 7: CFFA3000 - USB using virtual Disk II in slot 6
Aux: Pacemark extended 80 col card.

**Comment by jormahonkanen** [comment] 2019-09-19 13:56
No difference with Apple's 80col/64k card in AUX.

Platinum //e IOU AMI 9022MHQ 344-0020-A Apple 82 Philippines
Enhanced //e IOU (S) 8325 344-0020-A Apple 82

**Comment by jormahonkanen** [comment] 2019-09-20 12:32
Tested with:
Apple //e enhanced 65c02 PAL

AUX - RamWorks III + VGA
Slot 1 - Fastchip //e
Slot 6 - Disk II interface + wDrive

The same crash happens. This really indicates there's something wrong with the Fastchip //e. The latest Total Replay image wont work either (on platinum) no menu screen is loaded up when Fastchip is installed. I am trying to get the cards re-flashed and see what difference that makes or not.

**Comment by jormahonkanen** [comment] 2019-09-22 17:12
qkumba managed to get Total Replay working with my Fastchip //e. Don't know yet what was causing it not working. Hopefully he shares the info at some level.

**Comment by roughana** [comment] 2019-09-28 23:08
qkumba confirmed that TR was using an undocumented opcode to detect if host was IIgs. They changed this detection routine to fix the issue.

However, that doesn't explain why it worked on some configurations and not others.

**Comment by roughana** [comment] 2019-09-28 23:10
Apparently, this REP trick was borrowed from John Brooks so a change to P8 is probably needed too.

**Comment by JohnMBrooks** [comment] 2019-09-28 23:33
REP #2 has documented behavior on 65c02 & 65816. On 6502 it is undocumented but effectively a NOP.

The problem is that FastChip does not execute this instruction as documented and instead uses it for internal purposes. IE, the FastChip is not 100% compatible.

**Comment by jormahonkanen** [comment] 2019-09-30 18:20
Both my Fastchips have 65816 CPU.

**Comment by roughana** [comment] 2019-09-30 22:47
Mine is 65C02-14

Jorma, perhaps yours treats it like IIgs and then the function that fails is IIgs specific code later?

Regards
Andrew

**Comment by jormahonkanen** [comment] 2019-10-01 04:23
> Mine is 65C02-14 Jorma, perhaps yours treats it like IIgs and then the function that fails is IIgs specific code later? Regards Andrew
> […](#)
> On 1 Oct 2019, at 4:20 am, jormahonkanen ***@***.***> wrote: Both my Fastchips have 65816 CPU. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Very much possible. Plamen is sending me 65c02 version of the Fastchip someday.

**Comment by jormahonkanen** [comment] 2019-10-01 12:42
65816 version wasn't supposed to be "out there" but i never had, so far i know of, any problems with it.

**Comment by roughana** [comment] 2019-10-01 13:35
Except that undocumented opcodes for 65c02 get processed ok on 65816. And assumptions about being a IIgs get made incorrectly which may lead to bad behaviour on non IIgs machine.

**Comment by jormahonkanen** [comment] 2019-10-14 15:59
alpha 7 boots fine

**Closed as completed** 2019-10-18 05:09 UTC

**Comment by roughana** [comment] 2019-10-18 12:27
What is the resolution for this? Did P8 2.5 alpha 7 use IIgs identifcation routine?

**Comment by JohnMBrooks** [comment] 2019-10-18 14:17
No software changes were made to fix FastChip. REP #2 is still used in Bitsy Bye to determine if $C029 can be safely changed (ie, machine is not a //c+). Code snippet below:

			ldx		#$ff-$20
:ZpLoop
			lda		InitZpEnd-$FF,x		;Init ZP vars
			sta		ZpMoveEnd-$FF&$FF,x
			inx
			bne		:ZpLoop				;Loop ends with Z=1
			rep		#2					;Clr Z. Test for 65816 CPU
			beq		:NotGS
			trb		IoNewVideo			;Disable SHR
:NotGS
