### ISSUE TITLE
Diskmaker 8 v1.1

### ISSUE THREAD

**Issue by locutus001** [ProDOS-8/ProDOS8-Testing#5] opened 2018-10-02 11:22 UTC
Error message

BUG?

ProDOS 8a1
## Description

Get error messages similar to this "MLI Error $43 from call $CA"
The first string would always change but the $CA wouldn't.

## Expected Behavior

Access the disk, or write to the disk as normal

## Actual Behavior

Get error messages similar to this "MLI Error $43 from call $CA"
The first string would always change but the $CA wouldn't.

## Possible Fix

I'm not sure.  Contact the developer of the program to see if he/she is willing to write a new version for this version of ProDOS

## Steps to Reproduce

1. Do any Disk Access with the program
2.
3.
4.

## Context

Can't use the program

## Your Environment

Using just ProDOS 8a1 and booting directly into the program

### Hardware:

Apple IIgs ROM 01 : 4mb of RAM, Reactive MicroDrive/Turbo, Apple Disk ][ Drive controller,
Apple IIgs ROM 03 : 4mb of RAM, Reactive MicroDrive/Turbo, Apple Disk ][ Drive Controller, Transwarp GS (all speeds were tested)

### ProDOS8 version:
ProDOS 8a1

**Comment by apple2geek** [comment] 2019-08-25 23:52
I ran into this as well, under ProDOS 2.5.0a2, although I've only seen it manifest at the Volume Name level.
What appears to be happening is that DiskMaker is not properly honoring the "length" nybble of the byte preceding the volume name.
Specific examples: a volume named "/FLOPPY" will have the byte #$F6 preceding the F, L, O, P, P, Y characters in block $2.  A volume named "/DISKMAKER" will have the byte #$F9, and so on.  DiskMaker, though, will display those volumes as having the names "FLOPPY@@@@@@@@@" and "DISKMAKER@@@@@@" in the "Disks" list (note the "@"s correspond to the #$00/NUL bytes trailing the volume name).  Selecting such volumes will throw the MLI errors in question.
Interestingly, if you name a volume with a full-15-character volume name, the name will display correctly (since it has valid, non-NUL characters in all 15 positions), and the above MLI errors do not occur in that case.

I haven't spent any significant time attempting to reproduce this behavior (yet) against any earlier versions of ProDOS, but if there's value in doing so, I can take the time.

**Comment by bobbimanners** [comment] 2019-08-30 03:50
I think something similar is going on in ProTerm 3.1 where it shows garbage after the volume name.  Sounds like the same issue to me.

**Comment by JohnMBrooks** [comment] 2019-08-30 11:48
Can you create an 800KB disk image with these various problem apps on it so I can repro and investigate?

**Comment by bobbimanners** [comment] 2019-08-30 16:34
Sure - I will make one this evening with DISKMAKER8, Protterm 3.1 and Kyan Pascal.  Any others?

**Comment by JohnMBrooks** [comment] 2019-08-30 16:38
Also Shrinkit and the main.dictionary file that isn't copying correctly.

**Comment by bobbimanners** [comment] 2019-08-30 17:45
Ah yes, and those too.  Will be interesting to see if the MAIN.DICTIONARY file is misbehaving on media other than a 32MB HDD partition.

**Comment by bobbimanners** [comment] 2019-08-31 05:02
Attached is a ZIP file with two 800k ProDOS disk images.

1) Volume name /PROBLEMS ... has DISKMAKER8 v1.1, Kyan Pascal and ProTerm 3.1
2) Volume name /PROBLEM2 ... has MAIN.DICTIONARY, CAT.DOCTOR and ShrinkIt 3.4

Hopefully the attachment works okay, otherwise I will email!

Incidentally I ran into the MLI error $56 when copying MAIN.DICTIONARY with CAT.DOCTOR using ProDOS 2.5.0a3 under the GSPort emulator.  Rebooted into ProDOS 2.4.2 and it copied without a problem.  This problem seems quite reproducible.

[problem-disks.zip](https://github.com/ProDOS-8/ProDOS8-Testing/files/3562089/problem-disks.zip)

**Comment by JohnMBrooks** [comment] 2019-09-01 07:58
Fixed in P8 2.5.0a4. Volume name length could be corrupt in ProDOS ONLINE calls.

Problem Disk was very helpful in finding and fixing this bug.

**Closed as completed by JohnMBrooks** 2019-09-01 07:58 UTC
